name: baxton

description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_screenutil: ^5.9.3
  flutter_easyloading: ^3.0.5
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  flutter_downloader: ^1.12.0
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.2
  pdf: ^3.10.8
  file_saver: ^0.2.0
  signature: ^5.2.1
  cached_network_image: ^3.4.1
  mime:
  flutter_intl_phone_field: ^0.0.7

  # Icons
  iconsax: ^0.0.8
  fl_chart: ^0.71.0
  percent_indicator: ^4.2.3

  # State Management
  get: ^4.6.6
  json_annotation: ^4.9.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  image_picker: ^1.1.2
  emoji_picker_flutter: ^4.3.0
  pin_code_fields: ^8.0.1
  http_parser: ^4.1.2
  path: ^1.9.1
  web_socket_channel: ^3.0.3
  firebase_core: ^3.15.1
  firebase_messaging: ^15.2.9
  open_file: ^3.5.10
  share_plus: ^7.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
      
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
