// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions]

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeThk-IcYNfZbiCVle6lzl1lyZOsRcoUo',
    appId: '1:1031905996293:web:049a47fc8f450ac33eb66c',
    messagingSenderId: '1031905996293',
    projectId: 'baxton-5291e',
    authDomain: 'baxton-5291e.firebaseapp.com',
    storageBucket: 'baxton-5291e.firebasestorage.app',
    measurementId: 'G-WFLLLE1T7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALCjd76HH1X7mIOOux6RDRyDB3kavi9qk',
    appId: '1:1031905996293:android:90f02639097e136a3eb66c',
    messagingSenderId: '1031905996293',
    projectId: 'baxton-5291e',
    storageBucket: 'baxton-5291e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7ZXy5d9gSCqykkUta7rXpUvTdcFZ2DhI',
    appId: '1:1031905996293:ios:6f50b91e2fe9801c3eb66c',
    messagingSenderId: '1031905996293',
    projectId: 'baxton-5291e',
    storageBucket: 'baxton-5291e.firebasestorage.app',
    iosBundleId: 'com.example.baxton',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7ZXy5d9gSCqykkUta7rXpUvTdcFZ2DhI',
    appId: '1:1031905996293:ios:6f50b91e2fe9801c3eb66c',
    messagingSenderId: '1031905996293',
    projectId: 'baxton-5291e',
    storageBucket: 'baxton-5291e.firebasestorage.app',
    iosBundleId: 'com.example.baxton',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeThk-IcYNfZbiCVle6lzl1lyZOsRcoUo',
    appId: '1:1031905996293:web:0a752cbc5e0ebb5f3eb66c',
    messagingSenderId: '1031905996293',
    projectId: 'baxton-5291e',
    authDomain: 'baxton-5291e.firebaseapp.com',
    storageBucket: 'baxton-5291e.firebasestorage.app',
    measurementId: 'G-WS2GLN8JTY',
  );
}
